before_script:
  - docker info

build_image:
  script:
    - docker login -u $GITLAB_REGISTRY_USER -p $GITLAB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/thecornershop/gitlab-ci-runner-auto-cleanup:$CI_COMMIT_REF_SLUG .
    - docker push registry.gitlab.com/thecornershop/gitlab-ci-runner-auto-cleanup:$CI_COMMIT_REF_SLUG
